{
 "title": "PerformanceCounterExporter",
 "time": { "from": "now-6h", "to": "now" },
 "refresh": "30s",
 "templating": {
  "list": [
   {
    "name": "instance",
    "label": "Instance",
    "query": "label_values(pce_system_up_time, instance)"
   }
  ]
 },
 "panels": [
  {
   "title": "Uptime",
   "type": "graph",
   "gridPos": { "h": 4, "w": 12, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "pce_system_up_time{instance=\"$instance\"}",
     "legendFormat": "uptime"
    }
   ]
  },
  {
   "title": "Memory Available Bytes",
   "type": "graph",
   "gridPos": { "h": 4, "w": 12, "x": 12, "y": 0 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "expr": "pce_memory_available_bytes{instance=\"$instance\"}"
    }
   ]
  },
  {
   "title": "Processor",
   "type": "graph",
   "gridPos": { "h": 4, "w": 12, "x": 0, "y": 4 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "expr": "pce_processor_information_pct_processor_time_total{instance=\"$instance\"}",
     "legendFormat": "total"
    },
    {
     "expr": "pce_processor_information_pct_privileged_time_total{instance=\"$instance\"}",
     "legendFormat": "privileged"
    }
   ]
  },
  {
   "title": "Memory Pages",
   "type": "graph",
   "gridPos": { "h": 4, "w": 12, "x": 12, "y": 4 },
   "yaxes": [
    { "format": "iops" }
   ],
   "targets": [
    {
     "expr": "pce_memory_pages_sec{instance=\"$instance\"}"
    }
   ]
  },
  {
   "title": "Processor Queue Length",
   "type": "graph",
   "gridPos": { "h": 4, "w": 12, "x": 0, "y": 8 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "pce_system_processor_queue_length{instance=\"$instance\"}"
    }
   ]
  },
  {
   "title": "Network I/O",
   "type": "graph",
   "gridPos": { "h": 4, "w": 12, "x": 12, "y": 8 },
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "expr": "pce_network_interface_bytes_total_sec{instance=\"$instance\"}",
     "legendFormat": "{{counter_instance_name}}"
    }
   ]
  },
  {
   "title": "Processor Context Switches",
   "type": "graph",
   "gridPos": { "h": 4, "w": 12, "x": 0, "y": 12 },
   "yaxes": [
    { "format": "ops" }
   ],
   "targets": [
    {
     "expr": "pce_system_context_switches_sec{instance=\"$instance\"}"
    }
   ]
  },
  {
   "title": "Network Output Queue Length",
   "type": "graph",
   "gridPos": { "h": 4, "w": 12, "x": 12, "y": 12 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "pce_network_interface_output_queue_length{instance=\"$instance\"}",
     "legendFormat": "{{counter_instance_name}}"
    }
   ]
  },
  {
   "title": "Disk",
   "type": "graph",
   "gridPos": { "h": 4, "w": 12, "x": 0, "y": 16 },
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "expr": "pce_logical_avg_disk_sec_read{instance=\"$instance\"}",
     "legendFormat": "{{counter_instance_name}} read bytes/sec"
    },
    {
     "expr": "-pce_logical_avg_disk_sec_write{instance=\"$instance\"}",
     "legendFormat": "{{counter_instance_name}} write bytes/sec"
    }
   ]
  },
  {
   "title": "TCPv4 Active Connections",
   "type": "graph",
   "gridPos": { "h": 4, "w": 12, "x": 12, "y": 16 },
   "yaxes": [
    { "format": "reqps" }
   ],
   "targets": [
    {
     "expr": "rate(pce_tcpv4_connections_active{instance=\"$instance\"}[5m])"
    }
   ]
  },
  {
   "title": "Disk Transfers",
   "type": "graph",
   "gridPos": { "h": 4, "w": 12, "x": 0, "y": 20 },
   "yaxes": [
    { "format": "iops" }
   ],
   "targets": [
    {
     "expr": "pce_logical_disk_disk_transfers_sec{instance=\"$instance\"}",
     "legendFormat": "{{counter_instance_name}}"
    }
   ]
  },
  {
   "title": "TCPv4 Passive Connections",
   "type": "graph",
   "gridPos": { "h": 4, "w": 12, "x": 12, "y": 20 },
   "yaxes": [
    { "format": "reqps" }
   ],
   "targets": [
    {
     "expr": "rate(pce_tcpv4_connections_passive{instance=\"$instance\"}[5m])"
    }
   ]
  },
  {
   "title": "Disk Free Space",
   "type": "graph",
   "gridPos": { "h": 4, "w": 12, "x": 0, "y": 24 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "expr": "pce_logical_disk_pct_free_space{instance=\"$instance\"}",
     "legendFormat": "{{counter_instance_name}}"
    }
   ]
  },
  {
   "title": "TCPv4 Connections Reset",
   "type": "graph",
   "gridPos": { "h": 4, "w": 12, "x": 12, "y": 24 },
   "yaxes": [
    { "format": "reqps" }
   ],
   "targets": [
    {
     "expr": "rate(pce_tcpv4_connections_reset{instance=\"$instance\"}[5m])"
    }
   ]
  },
  {
   "title": "TCPv4 Connection Failures",
   "type": "graph",
   "gridPos": { "h": 4, "w": 12, "x": 12, "y": 28 },
   "yaxes": [
    { "format": "reqps" }
   ],
   "targets": [
    {
     "expr": "rate(pce_tcpv4_connection_failures{instance=\"$instance\"}[5m])"
    }
   ]
  },
  {
   "title": "TCPv4 Established Connections",
   "type": "graph",
   "gridPos": { "h": 4, "w": 12, "x": 12, "y": 32 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "pce_tcpv4_connections_established{instance=\"$instance\"}"
    }
   ]
  }
 ]
}